[server]
address = "0.0.0.0"
port = 8501
maxUploadSize = 500
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#ff005a"
backgroundColor = "#f3f6f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#102b45"
font = "sans serif"
